### ISSUE TITLE
CLI crashes with `ts.parseConfigFileTextToJson is not a function` on TypeScript 7

### ISSUE THREAD

**Issue by byrnehollander** [0no-co/gql.tada#572]
### Describe the bug

In a project with TypeScript 7 installed, `gql.tada generate-output` crashes before doing any work:

```
TypeError: ts.parseConfigFileTextToJson is not a function
```

TypeScript 7 no longer exposes the legacy JS compiler API from the `typescript` package's top-level export (a stable programmatic API is planned for 7.1+), and `@gql.tada/internal`'s `readTSConfigFile` uses `ts.parseConfigFileTextToJson` to read `tsconfig.json`. So loading the plugin config fails even though this path only needs to parse JSONC, not run a compiler. `gql.tada generate schema` hits the same crash when it infers the output location from config.

Commands that build a TypeScript program (`check`, `scan`, `turbo`, `generate-persisted`, `doctor`) also depend on the removed API, but that's a larger migration — this issue is only about the config-loading crash. I have a fix for it and will open a PR shortly.

### Reproduction

```sh
mkdir ts7-repro && cd ts7-repro
npm init -y
npm install typescript@7.0.2 gql.tada graphql
cat > tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "strict": true,
    "plugins": [
      {
        "name": "gql.tada/ts-plugin",
        "schema": "./schema.graphql",
        "tadaOutputLocation": "./src/graphql-env.d.ts"
      }
    ]
  }
}
EOF
echo 'type Query { hello: String }' > schema.graphql
npx gql.tada generate-output
```

Expected: `src/graphql-env.d.ts` is written.
Actual: `TypeError: ts.parseConfigFileTextToJson is not a function`

The same steps work with `typescript@5` or `typescript@6.0.0-beta`.

### gql.tada version

`gql.tada@1.11.2` (`typescript@7.0.2`)

### Validations

- [x] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [x] Read the [docs](https://gql-tada.0no.co/).
- [x] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by simultsop** [comment]
Will this be patched soon or do we have to downgrade ts?

**Comment by FlavioScimeca** [comment]
i have done this trick, is not the best solution but it works, you can find also other stuff:
https://github.com/FlavioScimeca/vyrel

**Comment by wfl-junior** [comment]
latest version 1.11.3 still has this problem
